rooseveltframework/generator-roosevelt

sampleApp/package.json

Replace Nodemon with Supervisor (Closes Issue #5)

---

sampleApp/package.json

Added ignore to node_modules for supervisor in sample app. Closing Issue #18

Added ignore to node_modules (Closing Issue #18)

---

sampleApp/package.json

Adding .git ignore to supervisor (Closes Issue #20)

---

mkroosevelt.js
package.json

Implemented the ability for the user to create an app in the current
directory by using `mkroosevelt .` (Closes Issue #22)

Create app in current directory (Closes Issue #22)

---

.eslintignore
mkroosevelt.js
package.json
sampleApp/mvc/models/global.js
sampleApp/package.json

Replaced JShint with Eslint and fixed accompanying errors. (Closes #6)

Replaced JShint with Eslint (Closes #6)

---

mkroosevelt.js

Removed deprecated `fs.existsSync` and added `fs.accessSync`. (Closes #25)

---

package.json
sampleApp/.gitignore
sampleApp/package.json

Related PR: https://github.com/kethinov/roosevelt/pull/98

Browserify support

---

generators/app/index.js
package-lock.json
package.json

This PR
- upgrade the generator from eslint 2.11.1 to 4.1.1
- fixes indentation errors to reflect eslint 4.1.1 requirements
- closes #71

upgrade to eslint 4.1.1 

---

generators/app/templates/templatedPackage.json

Added a line in the templatedPackage.json for calling the HTML validator's kill script.
**This merge request goes hand in hand with [THIS](https://github.com/rooseveltframework/roosevelt/pull/171) pull request and should not be merged until the other pull request has been merged.**

Added line in templatedPackage.json for validator kill script

---

generators/app/index.js
generators/app/templates/templatedPackage.json
rooseveltDefaults.json

This PR coincides with https://github.com/rooseveltframework/roosevelt/pull/207
- Adds params which have been missing
- Adds new params introduced in https://github.com/rooseveltframework/roosevelt/pull/207
- Fixes multitude of linting errors

Add missing defaults and fix linting errors

---

generators/app/index.js
generators/app/templates/app.js
generators/app/templates/mvc/controllers/404.js
generators/app/templates/mvc/controllers/homepage.js
generators/app/templates/mvc/controllers/robots.txt.js
generators/app/templates/mvc/models/global.js
generators/app/templates/statics/js/main.js
generators/app/templates/templatedPackage.json
package-lock.json
package.json
rooseveltDefaults.json
unitTest.js

This PR updates the generator to account for the latest scripts and param changes added to Roosevelt.
Since these alterations to Roosevelt haven't been badged to a release version yet this PR may need to be updated to account for that version bump prior to being merged.

Add params for latest roosevelt and use standard for linting

---

package.json

fix(package): update node-forge to version 0.7.5

---

generators/app/index.js

Small typo fix that allows HTTPS to be enabled in package.json (Closes #128)

HTTPS enable fix

---

README.md
package.json

fix scripts and add codecov badge

---

appveyor.yml
generators/app/index.js
generators/app/promptingHelpers.js
package-lock.json
test/unit/options.js
test/unit/promptHelpers.js
test/unit/prompts.js

Some of the prompt unit tests. (Closes #131 )

Unit Testing (In Progress)

---

package-lock.json
package.json
test/unit/options.js

This pull request:
- Updates ESlint
- Updates Standard
- Updates NYC
- Updates lint-staged
- Lints against standard

Updates for ESlint and Standard

---

generators/app/templates/_package.json
generators/app/templates/defaults.json

This updates `_package.json` and `defaults.json` settings to reflect the new release of roosevelt and also updates other outdated dependencies that are generated after running the generator.
Closes #166

Updates for roosevelt 0.12.0

---

generators/app/templates/_package.json
generators/app/templates/defaults.json
generators/app/templates/mvc/controllers/robots.txt.js
generators/app/templates/mvc/controllers/teddy/404.js
generators/app/templates/mvc/controllers/teddy/homepage.js
generators/app/templates/mvc/controllers/vanilla/homepage.js

Updated the Roosevelt dependency to the latest release (v0.13.0).

Updated to the latest Roosevelt Release

---

CHANGELOG.md
generators/app/index.js
generators/app/templates/_package.json
generators/app/templates/defaults.json
package-lock.json
package.json
test/unit/prompts.js

This PR: 
- Updates the generator to latest version of Roosevelt (v.14)
- Fixes outdated http params (closes #208) 
- Fixes one liner dependency print (closes #172)
- Updates logger params to latest
- Updates CHANGELOG
- Add dev-install and dev-prune scripts

Update roosevelt params and prettify json

---

generators/app/index.js

closes #332
closes #376
closes #375

closes #332

---

generators/app/index.js

https://github.com/rooseveltframework/mkroosevelt/issues/70

mkroosevelt fix for issue #70

---

test/unit/prompts.js

Changed withPrompts to withAnswer in test/unit/prompts.js, test is passing, no errors. I also ran standard to fix linter errors.

Changed withPrompts to withAnswer 

---

CONTRIBUTING.md

The removed section is no longer true.

docs update
